// Autogenerated from Pigeon (v9.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Chat;

@interface Chat : NSObject
+ (instancetype)makeWithMessage:(nullable NSString *)message
    clients:(nullable NSString *)clients;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, copy, nullable) NSString * clients;
@end

/// The codec used by ChatApi.
NSObject<FlutterMessageCodec> *ChatApiGetCodec(void);

@protocol ChatApi
/// @return `nil` only when `error != nil`.
- (nullable NSArray<Chat *> *)searchKeyword:(NSString *)keyword error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ChatApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChatApi> *_Nullable api);

NS_ASSUME_NONNULL_END
